export {default as article } from './article.js'
export {default as magazine } from './magazine.js'
export {default as user } from './user.js'
export {default as favorite } from './favorite.js'
export {default as admin } from './admin.js'