export { default as articleRouter } from './articles.js'
export { default as magazineRouter } from './magazine.js'
export { default as userRouter } from './user.js'
export { default as favoriteRouter } from './favorite.js'
export { default as adminRouter } from './admin.js'